al::LayoutActor
sead::SafeString al::LayoutActor::mName
NerveKeeper* al::LayoutActor::mNerveKeeper
Referenced by getNerveKeeper, initNerve.
AudioKeeper* al::LayoutActor::mAudioKeeper
Referenced by getAudioKeeper.
EffectKeeper* al::LayoutActor::mEffectKeeper
Referenced by getEffectKeeper.
void* al::LayoutActor::_20
void* al::LayoutActor::_24
void* al::LayoutActor::_28
bool al::LayoutActor::mIsAlive
Referenced by appear, kill.
void al::LayoutActor::initNerve(const Nerve *nerve, int maxNerveStates=0)
References mNerveKeeper.
Referenced by al::WipeSimple::WipeSimple.
NerveKeeper * al::LayoutActor::getNerveKeeper() const
References mNerveKeeper.
void al::LayoutActor::appear()
References calcAnim, mIsAlive.
Referenced by al::WipeSimple::appear.
void al::LayoutActor::kill()
References getEffectKeeper, mIsAlive.
Referenced by al::WipeSimple::exeOpen.
virtual void al::LayoutActor::movement()
virtual void al::LayoutActor::calcAnim()
Referenced by appear.
AudioKeeper * al::LayoutActor::getAudioKeeper() const
References mAudioKeeper.
EffectKeeper * al::LayoutActor::getEffectKeeper() const
References mEffectKeeper.
Referenced by kill.
void al::LayoutActor::control()
virtual void al::LayoutActor::unk1()
virtual void al::LayoutActor::unk2()
al::LayoutActor::LayoutActor(const char *name)