al::ActorPoseKeeperBase
sead::Vector3f al::ActorPoseKeeperBase::mTrans
Referenced by getTrans, getTransPtr.
const sead::Vector3f al::ActorPoseKeeperBase::sDefaultGravity
Referenced by getGravity.
const sead::Vector3f & al::ActorPoseKeeperBase::getTrans() const
References mTrans.
Referenced by al::getTrans.
const sead::Vector3f & al::ActorPoseKeeperBase::getRotate() const
Referenced by al::getRotate.
const sead::Vector3f & al::ActorPoseKeeperBase::getScale() const
Referenced by alLiveActorFunction::calcAnimDirect, al::getScale.
const sead::Vector3f & al::ActorPoseKeeperBase::getVelocity() const
Referenced by al::getVelocity.
const sead::Vector3f & al::ActorPoseKeeperBase::getFront() const
Referenced by al::getFront.
const sead::Quatf & al::ActorPoseKeeperBase::getQuat() const
Referenced by al::getQuat.
const sead::Vector3f & al::ActorPoseKeeperBase::getGravity() const
References sDefaultGravity.
Referenced by al::getGravity.
sead::Vector3f * al::ActorPoseKeeperBase::getTransPtr()
References mTrans.
Referenced by al::getTransPtr, al::setTrans.
sead::Vector3f * al::ActorPoseKeeperBase::getRotatePtr()
Referenced by al::getRotatePtr, al::setRotate.
sead::Vector3f * al::ActorPoseKeeperBase::getScalePtr()
Referenced by al::getScalePtr, al::setScale.
sead::Vector3f * al::ActorPoseKeeperBase::getVelocityPtr()
Referenced by al::getVelocityPtr, al::setVelocity, al::setVelocityZero.
sead::Vector3f * al::ActorPoseKeeperBase::getFrontPtr()
Referenced by al::getFrontPtr, al::setFront.
sead::Quatf * al::ActorPoseKeeperBase::getQuatPtr()
Referenced by al::getQuatPtr, al::setQuat.
sead::Vector3f * al::ActorPoseKeeperBase::getGravityPtr()
Referenced by al::getGravityPtr, al::setGravity.
virtual void al::ActorPoseKeeperBase::updatePoseRotate(const sead::Vector3f &rot)=0
Referenced by al::updatePoseRotate.
virtual void al::ActorPoseKeeperBase::updatePoseQuat(const sead::Quatf &quat)=0
Referenced by al::updatePoseQuat.
virtual void al::ActorPoseKeeperBase::updatePoseMtx(const sead::Matrix34f *mtx)=0
Referenced by al::updatePoseMtx.
virtual void al::ActorPoseKeeperBase::copyPose(const ActorPoseKeeperBase *from)
virtual void al::ActorPoseKeeperBase::calcBaseMtx(sead::Matrix34f *out)=0
Referenced by alLiveActorFunction::calcAnimDirect, alActorPoseFunction::calcBaseMtx, al::calcFrontDir, al::calcSideDir, al::calcUpDir.
al::ActorPoseKeeperBase::ActorPoseKeeperBase()