al::ByamlIter
const u8* al::ByamlIter::mData
Referenced by ByamlIter, getKeyIndex, isValid.
const ByamlHeader* al::ByamlIter::mHeader
Referenced by ByamlIter, getHeader, getKeyIndex.
const u8* al::ByamlIter::mRootNode
Referenced by ByamlIter, getByamlDataByKey.
const ByamlContainerHeader* al::ByamlIter::mContainerHeader
Referenced by getSize, isTypeArray, isTypeContainer, isTypeHash.
union al::ByamlIter al::ByamlIter
union al::ByamlIter al::ByamlIter
const ByamlHeader * al::ByamlIter::getHeader() const
References mHeader.
bool al::ByamlIter::isEqualData(const ByamlIter &other) const
bool al::ByamlIter::isValid() const
References mData.
bool al::ByamlIter::isTypeArray() const
References al::ByamlDataType_Array, mContainerHeader.
bool al::ByamlIter::isTypeHash() const
References al::ByamlDataType_Hash, mContainerHeader.
Referenced by getByamlDataByKey.
bool al::ByamlIter::isTypeContainer() const
References al::ByamlDataType_Array, al::ByamlDataType_Hash, mContainerHeader.
Referenced by getSize.
int al::ByamlIter::getSize() const
References isTypeContainer, mContainerHeader.
bool al::ByamlIter::isExistKey(const char *key) const
int al::ByamlIter::getKeyIndex(const char *key) const
References mData, mHeader.
Referenced by getByamlDataByKey.
bool al::ByamlIter::getKeyName(const char **out, int index) const
bool al::ByamlIter::getByamlDataByIndex(ByamlData *out, int index) const
bool al::ByamlIter::getByamlDataByKey(ByamlData *out, const char *key) const
References al::ByamlHashIter::getDataByKey, getKeyIndex, isTypeHash, mRootNode.
Referenced by tryGetBoolByKey, tryGetFloatByKey, tryGetIntByKey.
bool al::ByamlIter::getByamlDataByKeyIndex(ByamlData *out, int index) const
bool al::ByamlIter::getByamlDataAndKeyName(ByamlData *out, const char **key, int index) const
bool al::ByamlIter::tryGetStringByIndex(const char **out, int index) const
bool al::ByamlIter::tryGetStringByKey(const char **out, const char *key) const
bool al::ByamlIter::tryGetBinaryByIndex(const u8 **out, int *size, int index) const
bool al::ByamlIter::tryGetBinaryByKey(const u8 **out, int *size, const char *key) const
ByamlIter al::ByamlIter::getIterByIndex(int index) const
bool al::ByamlIter::tryGetIterByIndex(ByamlIter *out, int index) const
ByamlIter al::ByamlIter::getIterByKey(const char *key) const
bool al::ByamlIter::tryGetIterByKey(ByamlIter *out, const char *key) const
bool al::ByamlIter::tryGetIterAndKeyNameByIndex(ByamlIter *out, const char **key, int index) const
bool al::ByamlIter::tryGetBoolByIndex(bool *out, int index) const
bool al::ByamlIter::tryGetBoolByKey(bool *out, const char *key) const
References getByamlDataByKey, tryConvertBool.
bool al::ByamlIter::tryGetIntByIndex(int *out, int index) const
bool al::ByamlIter::tryGetIntByKey(int *out, const char *key) const
References getByamlDataByKey, tryConvertInt.
Referenced by alPlacementFunction::getClippingViewId.
bool al::ByamlIter::tryGetFloatByIndex(float *out, int index) const
bool al::ByamlIter::tryGetFloatByKey(float *out, const char *key) const
References getByamlDataByKey, tryConvertFloat.
bool al::ByamlIter::tryConvertString(const char **out, const ByamlData *data) const
bool al::ByamlIter::tryConvertBinary(const u8 **out, int *size, const ByamlData *data) const
bool al::ByamlIter::tryConvertIter(ByamlIter *iter, const ByamlData *data) const
bool al::ByamlIter::tryConvertBool(bool *out, const ByamlData *data) const
References al::ByamlDataType_Bool, al::ByamlDataType_Int.
Referenced by tryGetBoolByKey.
bool al::ByamlIter::tryConvertInt(int *out, const ByamlData *data) const
References al::ByamlDataType_Int.
Referenced by tryGetIntByKey.
bool al::ByamlIter::tryConvertFloat(float *out, const ByamlData *data) const
References al::ByamlDataType_Float.
Referenced by tryGetFloatByKey.
al::ByamlIter::ByamlIter()
al::ByamlIter::ByamlIter(const ByamlIter &other)
al::ByamlIter::ByamlIter(const u8 *data)
References mData, mHeader, mRootNode, alByamlLocalUtil::verifiByaml.
al::ByamlIter::ByamlIter(const u8 *data, const u8 *rootNode)