Application
friend class ApplicationFunction
void* Application::_10
al::GameFrameworkCtr* Application::mGameFramework
al::SystemKit* Application::mSystemKit
Referenced by getSystemKit.
u8 Application::_1C[24][24]
u8 Application::_34[24][24]
void* Application::_4C
al::SceneObjHolder* Application::mSceneObjHolder
Referenced by getSceneObjHolder, setSceneObjHolder.
al::LiveActorKit* Application::mLiveActorKit
Referenced by getLiveActorKit, setLiveActorKit.
void* Application::mEffectUserInfo
PlayerActor* Application::mPlayerActor
Referenced by getPlayerActor.
al::SceneObjHolder * Application::getSceneObjHolder() const
References mSceneObjHolder.
Referenced by al::getSceneObjHolder.
void Application::setSceneObjHolder(al::SceneObjHolder *holder)
References mSceneObjHolder.
al::LiveActorKit * Application::getLiveActorKit() const
References mLiveActorKit.
Referenced by al::getLiveActorKit.
void Application::setLiveActorKit(al::LiveActorKit *holder)
References mLiveActorKit.
Referenced by al::initLiveActorKit.
al::SystemKit * Application::getSystemKit() const
References mSystemKit.
Referenced by alProjectInterface::getSystemKit.
PlayerActor * Application::getPlayerActor() const
References mPlayerActor.
RootTask * Application::getRootTask() const
void Application::init()
void Application::run()