al::ByamlHashIter
const u8* al::ByamlHashIter::mData
Referenced by findPair.
uintptr_t al::ByamlHashIter::mDataPtr
Referenced by getPairTable.
const Header* al::ByamlHashIter::mHeader
Referenced by getSize.
union al::ByamlHashIter al::ByamlHashIter
const ByamlHashPair * al::ByamlHashIter::getPairTable() const
References mDataPtr.
Referenced by findPair.
u32 al::ByamlHashIter::getSize() const
References mHeader.
Referenced by findPair.
al::ByamlHashIter::ByamlHashIter(const u8 *data)
const ByamlHashPair * al::ByamlHashIter::findPair(int keyIdx) const
References getPairTable, getSize, mData.
bool al::ByamlHashIter::getDataByKey(ByamlData *out, int index) const
Referenced by al::ByamlIter::getByamlDataByKey.