al::SceneObjHolder
typedef ISceneObj *(* al::SceneObjHolder::CreateFunc) (int id))(int id)
CreateFunc al::SceneObjHolder::mCreateFunc
Referenced by create.
ISceneObj** al::SceneObjHolder::mObjs
Referenced by create, getObj, initAfterPlacementSceneObj, isExist, setObj.
int al::SceneObjHolder::mSize
Referenced by initAfterPlacementSceneObj.
ISceneObj * al::SceneObjHolder::create(int id)
References mCreateFunc, mObjs.
Referenced by al::createSceneObj.
ISceneObj * al::SceneObjHolder::getObj(int id) const
References mObjs.
Referenced by al::getSceneObj.
bool al::SceneObjHolder::isExist(int id) const
References mObjs.
Referenced by al::isExistSceneObj.
void al::SceneObjHolder::setObj(ISceneObj *obj, int id)
References mObjs.
Referenced by al::setSceneObj.
void al::SceneObjHolder::initAfterPlacementSceneObj(const ActorInitInfo &info)
References al::ISceneObj::initAfterPlacementSceneObj, mObjs, mSize.
Referenced by al::Scene::endInit.
al::SceneObjHolder::SceneObjHolder(CreateFunc func, int size)