al::SystemKit
MemorySystem* al::SystemKit::mMemorySystem
Referenced by getMemorySystem.
FileLoader* al::SystemKit::mFileLoader
Referenced by createFileLoader, getFileLoader.
void* al::SystemKit::_8
SaveDataDirector* al::SystemKit::mSaveDataDirector
Referenced by createSaveDataSystem, getSaveDataDirector.
void* al::SystemKit::_10[7][7]
MemorySystem * al::SystemKit::getMemorySystem() const
References mMemorySystem.
Referenced by al::getCourseSelectHeap, al::getSceneResourceHeap, al::getSequenceHeap, al::getStationedHeap.
FileLoader * al::SystemKit::getFileLoader() const
References mFileLoader.
Referenced by al::loadArchive.
SaveDataDirector * al::SystemKit::getSaveDataDirector() const
References mSaveDataDirector.
void al::SystemKit::createFileLoader(int r1)
References mFileLoader.
void al::SystemKit::createSaveDataSystem(u32 r1, s32 r2)
References mSaveDataDirector.