al::HitSensorKeeper
sead::PtrArray<HitSensor> al::HitSensorKeeper::mSensors
Referenced by attackSensor, getSensor, invalidate, invalidateBySystem, update, validate, validateBySystem.
HitSensor * al::HitSensorKeeper::getSensor(const char *name) const
References al::isEqualString, mSensors.
Referenced by al::getHitSensor.
void al::HitSensorKeeper::attackSensor()
References al::isDead, mSensors.
void al::HitSensorKeeper::validate()
References mSensors.
void al::HitSensorKeeper::invalidate()
References mSensors.
void al::HitSensorKeeper::validateBySystem()
References mSensors.
Referenced by al::onDrawClipping.
void al::HitSensorKeeper::invalidateBySystem()
References mSensors.
void al::HitSensorKeeper::update()
References mSensors.
Referenced by alSensorFunction::updateHitSensorsAll.