al::RailRider
Rail* al::RailRider::mRail
Referenced by isReachedGoal, moveToNearestRail, moveToRailStart, RailRider.
sead::Vector3f al::RailRider::mCurrentPos
Referenced by getCurrentPos, moveToNearestRail, moveToRailStart, RailRider.
sead::Vector3f al::RailRider::mCurrentDir
Referenced by getCurrentDir, moveToNearestRail, moveToRailStart, RailRider.
float al::RailRider::_1C
Referenced by isReachedGoal, moveToNearestRail, moveToRailStart, RailRider.
float al::RailRider::mSpeed
Referenced by setSpeed.
bool al::RailRider::mIsLoop
Referenced by isLoop.
void al::RailRider::moveToRailStart()
References _1C, al::Rail::calcPosDir, mCurrentDir, mCurrentPos, mRail, al::Rail::normalizeLength.
Referenced by al::setSyncRailToStart.
void al::RailRider::moveToNearestRail(const sead::Vector3f &r1)
References _1C, al::Rail::calcNearestRailPosCoord, al::Rail::calcPosDir, mCurrentDir, mCurrentPos, mRail, al::Rail::normalizeLength.
bool al::RailRider::isReachedGoal() const
References _1C, al::Rail::getTotalLength, al::Rail::isClosed, al::isNearZero, mRail.
Referenced by al::isRailReachedGoal.
void al::RailRider::setSpeed(float speed)
References mSpeed.
const sead::Vector3f & al::RailRider::getCurrentPos() const
References mCurrentPos.
Referenced by al::setSyncRailToStart.
const sead::Vector3f & al::RailRider::getCurrentDir() const
References mCurrentDir.
Referenced by al::getRailDir.
bool al::RailRider::isLoop() const
References mIsLoop.
Referenced by al::isLoopRail.
al::RailRider::RailRider(Rail *rail)
References _1C, al::Rail::calcPosDir, mCurrentDir, mCurrentPos, mRail, al::Rail::normalizeLength.