al::RailKeeper
Rail* al::RailKeeper::mRail
Referenced by getRail, isExistRail, RailKeeper.
RailRider* al::RailKeeper::mRailRider
Referenced by getRailRider, RailKeeper.
Rail * al::RailKeeper::getRail()
References mRail.
RailRider * al::RailKeeper::getRailRider()
References mRailRider.
Referenced by al::getRailDir, al::isLoopRail, al::isRailReachedGoal, al::setSyncRailToStart.
bool al::RailKeeper::isExistRail() const
References mRail.
Referenced by al::isExistRail.
RailKeeper * tryCreateRailKeeper(const PlacementInfo &info)
al::RailKeeper::RailKeeper(const PlacementInfo &info)
References al::Rail::init, mRail, mRailRider.