al::MemorySystem
sead::ExpHeap* al::MemorySystem::mStationedHeap
Referenced by getStationedHeap.
sead::Heap* al::MemorySystem::_4
sead::ExpHeap* al::MemorySystem::mSequenceHeap
Referenced by createSequenceHeap, freeAllSequenceHeap, getSequenceHeap.
sead::FrameHeap* al::MemorySystem::mSceneResourceHeap
Referenced by createSceneResourceHeap, getSceneResourceHeap.
sead::FrameHeap* al::MemorySystem::mSceneHeap
Referenced by getSceneHeap.
sead::Heap* al::MemorySystem::_14
sead::FrameHeap* al::MemorySystem::mCourseSelectResourceHeap
sead::FrameHeap* al::MemorySystem::mCourseSelectHeap
Referenced by getCourseSelectHeap.
u8 al::MemorySystem::unk1[0x20][0x20]
sead::ExpHeap * al::MemorySystem::getStationedHeap() const
References mStationedHeap.
Referenced by al::getStationedHeap.
sead::ExpHeap * al::MemorySystem::getSequenceHeap() const
References mSequenceHeap.
Referenced by al::getSequenceHeap.
sead::FrameHeap * al::MemorySystem::getSceneResourceHeap() const
References mSceneResourceHeap.
Referenced by al::getSceneResourceHeap.
sead::FrameHeap * al::MemorySystem::getSceneHeap() const
References mSceneHeap.
sead::FrameHeap * al::MemorySystem::getCourseSelectHeap() const
References mCourseSelectHeap.
Referenced by al::getCourseSelectHeap.
void al::MemorySystem::createSequenceHeap()
References mSequenceHeap.
void al::MemorySystem::createSceneHeap(const char *stageName)
void al::MemorySystem::createSceneResourceHeap(const char *stageName)
References al::findOrCreateResource, al::fn_002911e8, al::isEqualString, mSceneResourceHeap.
void al::MemorySystem::destroySceneHeap(bool destroyResource)
void al::MemorySystem::destroyCourseSelect()
void al::MemorySystem::freeAllSequenceHeap()
References mSequenceHeap.