al::Scene
AudioKeeper* al::Scene::mAudioKeeper
Referenced by getAudioKeeper, movement.
LiveActorKit* al::Scene::mLiveActorKit
LayoutKit* al::Scene::mLayoutKit
SceneObjHolder* al::Scene::mSceneObjHolder
Referenced by endInit, initSceneObjHolder.
ActorFactory* al::Scene::mActorFactory
Referenced by getActorFactory, initActorFactory.
void* al::Scene::_20
StageResourceKeeper* al::Scene::mResourceKeeper
Referenced by initAndLoadStageResource.
void* al::Scene::_28
void* al::Scene::_2C
bool al::Scene::mIsAlive
Referenced by appear, isAlive, kill, movement.
bool al::Scene::isAlive() const
References mIsAlive.
ActorFactory * al::Scene::getActorFactory() const
References mActorFactory.
void al::Scene::initAndLoadStageResource(const char *stageName, int scenario, sead::Heap *heap)
References al::StageResourceKeeper::initAndLoadResource, mResourceKeeper.
void al::Scene::initSceneAudio(const char *stageName, int scenario, int, const sead::SafeString &, const char *userName)
void al::Scene::initCameraDirector()
void al::Scene::initActorFactory()
References mActorFactory.
void al::Scene::initSceneObjHolder()
References mSceneObjHolder.
void al::Scene::initLiveActorKit()
void al::Scene::initLayoutKit()
void al::Scene::endInit(const ActorInitInfo &info)
References al::SceneObjHolder::initAfterPlacementSceneObj, mSceneObjHolder.
void al::Scene::appear()
References mIsAlive.
void al::Scene::kill()
References mIsAlive.
virtual void al::Scene::init()=0
void al::Scene::movement()
References control, mAudioKeeper, mIsAlive, al::AudioKeeper::update, al::NerveExecutor::updateNerve.
void al::Scene::control()
Referenced by movement.
virtual void al::Scene::drawMainTop()
Referenced by al::Sequence::unk1.
virtual void al::Scene::drawSubTop()
Referenced by al::Sequence::unk2.
virtual void al::Scene::drawMainBottom()
Referenced by al::Sequence::unk3.
virtual void al::Scene::drawSubButtom()
virtual void al::Scene::unk5()
virtual void al::Scene::unk6()
virtual void al::Scene::unk7()
AudioKeeper * al::Scene::getAudioKeeper() const
References mAudioKeeper.
virtual void al::Scene::unk8()
virtual void al::Scene::draw3D()
virtual void al::Scene::drawEffect()
al::Scene::Scene(const char *name)