al::ExecuteDirector
friend class LayoutKit
size_t al::ExecuteDirector::_0
Referenced by init.
ExecuteTableHolderUpdate* al::ExecuteDirector::mUpdateTable
Referenced by createExecutorListTable, init, registerFunctor, registerUser.
int al::ExecuteDirector::mDrawTableAmount
Referenced by createExecutorListTable, init, registerFunctor, registerFunctorDraw, registerUser.
ExecuteTableHolderDraw** al::ExecuteDirector::mDrawTables
Referenced by createExecutorListTable, init, registerFunctor, registerFunctorDraw, registerUser.
ExecuteRequestKeeper* al::ExecuteDirector::mRequestKeeper
Referenced by init.
void* al::ExecuteDirector::_14
Referenced by init.
void* al::ExecuteDirector::_18
Referenced by al::LayoutKit::createExecuteDirector, init.
void al::ExecuteDirector::init()
References _0, _14, _18, al::ExecuteTableHolderDraw::init, al::ExecuteTableHolderUpdate::init, mDrawTableAmount, mDrawTables, mRequestKeeper, mUpdateTable.
Referenced by al::LayoutKit::createExecuteDirector.
void al::ExecuteDirector::createExecutorListTable()
References createExecutorListTable, al::ExecuteTableHolderUpdate::createExecutorListTable, mDrawTableAmount, mDrawTables, mUpdateTable.
Referenced by createExecutorListTable, al::LiveActorKit::endInit.
void al::ExecuteDirector::registerUser(al::IUseExecutor *p, const char *str)
References mDrawTableAmount, mDrawTables, mUpdateTable, al::ExecuteTableHolderUpdate::tryRegisterUser.
Referenced by al::registerExecutorUser.
void al::ExecuteDirector::registerFunctor(const al::FunctorBase &base, const char *str)
References mDrawTableAmount, mDrawTables, mUpdateTable, al::ExecuteTableHolderUpdate::tryRegisterFunctor.
Referenced by al::registerExecutorFunctor.
void al::ExecuteDirector::registerFunctorDraw(const al::FunctorBase &base, const char *str)
References mDrawTableAmount, mDrawTables.
Referenced by al::registerExecutorFunctorDraw.
al::ExecuteDirector::ExecuteDirector(int)