al::SensorHitGroup
sead::PtrArray<HitSensor> al::SensorHitGroup::mSensors
Referenced by add.
void al::SensorHitGroup::add(HitSensor *sensor)
References mSensors.
Referenced by al::HitSensor::validate, al::HitSensor::validateBySystem.
void al::SensorHitGroup::remove(HitSensor *sensor)
Referenced by al::HitSensor::invalidate, al::HitSensor::invalidateBySystem.
al::SensorHitGroup::SensorHitGroup(int, const char *name)