al::LiveActorKit
int al::LiveActorKit::mAllActorsBufferSize
Referenced by LiveActorKit.
ExecuteDirector* al::LiveActorKit::mExecuteDirector
Referenced by endInit, getExecuteDirector.
EffectSystem* al::LiveActorKit::mEffectSystem
Referenced by endInit.
void* al::LiveActorKit::_C
void* al::LiveActorKit::_10
FogDirector* al::LiveActorKit::mFogDirector
Referenced by endInit.
void* al::LiveActorKit::_18
void* al::LiveActorKit::_1C
void* al::LiveActorKit::_20
ClippingDirector* al::LiveActorKit::mClippingDirector
Referenced by endInit, getClippingDirector.
CollisionDirector* al::LiveActorKit::mCollisionDirector
Referenced by endInit.
HitSensorDirector* al::LiveActorKit::mHitSensorDirector
void* al::LiveActorKit::_30
void* al::LiveActorKit::_34
void* al::LiveActorKit::_38
LiveActorGroup* al::LiveActorKit::mAllActors
Referenced by endInit, getAllActors, LiveActorKit.
void* al::LiveActorKit::_40
ClippingDirector * al::LiveActorKit::getClippingDirector() const
References mClippingDirector.
Referenced by al::invalidateClipping, al::validateClipping.
ExecuteDirector * al::LiveActorKit::getExecuteDirector() const
References mExecuteDirector.
Referenced by al::registerExecutorFunctor, al::registerExecutorFunctorDraw, al::registerExecutorUser.
LiveActorGroup * al::LiveActorKit::getAllActors() const
References mAllActors.
Referenced by al::LiveActor::LiveActor.
void al::LiveActorKit::update()
void al::LiveActorKit::endInit()
References al::ExecuteDirector::createExecutorListTable, al::ClippingDirector::endInit, al::CollisionDirector::endInit, al::FogDirector::endInit, al::fn_001cc9b0, al::fn_001e8a64, al::fn_00240350, al::LiveActorGroup::getArray, mAllActors, mClippingDirector, mCollisionDirector, mEffectSystem, mExecuteDirector, mFogDirector, al::EffectSystem::startScene.
al::LiveActorKit::LiveActorKit(int groupBufSize)
References mAllActors, mAllActorsBufferSize.