al::Rail
int al::Rail::_0
int al::Rail::_4
int al::Rail::_8
int al::Rail::_C
bool al::Rail::mIsClosed
Referenced by isClosed.
bool al::Rail::isClosed() const
References mIsClosed.
Referenced by al::RailRider::isReachedGoal.
void al::Rail::init(const PlacementInfo &info)
Referenced by al::RailKeeper::RailKeeper.
float al::Rail::getTotalLength() const
Referenced by al::RailRider::isReachedGoal.
float al::Rail::normalizeLength(float) const
Referenced by al::RailRider::moveToNearestRail, al::RailRider::moveToRailStart, al::RailRider::RailRider.
void al::Rail::calcPosDir(sead::Vector3f *, sead::Vector3f *, float)
Referenced by al::RailRider::moveToNearestRail, al::RailRider::moveToRailStart, al::RailRider::RailRider.
float al::Rail::calcNearestRailPosCoord(const sead::Vector3f &, float)
Referenced by al::RailRider::moveToNearestRail.
al::Rail::Rail()