al::ClippingDirector
int al::ClippingDirector::_4
ClippingActorHolder* al::ClippingDirector::mClippingActorHolder
Referenced by getClippingActorHolder.
void* al::ClippingDirector::_C
void* al::ClippingDirector::_10
void al::ClippingDirector::endInit()
Referenced by al::LiveActorKit::endInit.
ClippingActorHolder * al::ClippingDirector::getClippingActorHolder()
References mClippingActorHolder.
Referenced by al::invalidateClipping, al::validateClipping.
virtual void al::ClippingDirector::execute()
al::ClippingDirector::ClippingDirector(int)