al::LiveActor
friend class ::alActorPoseFunction
friend class ::alLiveActorFunction
const char* al::LiveActor::mActorName
Referenced by getName.
LiveActorFlag al::LiveActor::mLiveActorFlag
Referenced by calcAnim, getLiveActorFlag, getLiveActorFlag.
ActorPoseKeeperBase* al::LiveActor::mActorPoseKeeper
Referenced by calcAnim, alLiveActorFunction::calcAnimDirect, alActorPoseFunction::calcBaseMtx, getActorPoseKeeper, initPoseKeeper.
ActorExecuteInfo* al::LiveActor::mActorExecuteInfo
Referenced by getActorExecuteInfo.
ActorActionKeeper* al::LiveActor::mActorActionKeeper
Referenced by getActorActionKeeper.
Collider* al::LiveActor::mCollider
Referenced by getCollider.
CollisionParts* al::LiveActor::mCollisionParts
Referenced by alLiveActorFunction::calcAnimDirect.
ModelKeeper* al::LiveActor::mModelKeeper
Referenced by alLiveActorFunction::calcAnimDirect, getModelKeeper.
NerveKeeper* al::LiveActor::mNerveKeeper
Referenced by getNerveKeeper, initNerveKeeper.
HitSensorKeeper* al::LiveActor::mHitSensorKeeper
Referenced by getHitSensorKeeper.
EffectKeeper* al::LiveActor::mEffectKeeper
Referenced by getEffectKeeper.
AudioKeeper* al::LiveActor::mAudioKeeper
Referenced by getAudioKeeper.
StageSwitchKeeper* al::LiveActor::mStageSwitchKeeper
Referenced by getStageSwitchKeeper, initStageSwitchKeeper.
RailKeeper* al::LiveActor::mRailKeeper
Referenced by getRailKeeper, initRailKeeper.
ShadowKeeper* al::LiveActor::mShadowKeeper
Referenced by getShadowKeeper.
ActorLightCtrl* al::LiveActor::mActorLightCtrl
void* al::LiveActor::_4C
SubActorKeeper* al::LiveActor::mSubActorKeeper
Referenced by alLiveActorFunction::calcAnimDirect.
const char * al::LiveActor::getName() const
References mActorName.
ActorPoseKeeperBase * al::LiveActor::getActorPoseKeeper() const
References mActorPoseKeeper.
Referenced by al::calcFrontDir, al::calcSideDir, al::calcUpDir, al::getFront, al::getFrontPtr, al::getGravity, al::getGravityPtr, al::getQuat, al::getQuatPtr, al::getRotate, al::getRotatePtr, al::getScale, al::getScalePtr, al::getTrans, al::getTransPtr, al::getVelocity, al::getVelocityPtr, al::setFront, al::setGravity, al::setQuat, al::setRotate, al::setScale, al::setTrans, al::setVelocity, al::setVelocityZero, al::updatePoseMtx, al::updatePoseQuat, al::updatePoseRotate.
ActorExecuteInfo * al::LiveActor::getActorExecuteInfo() const
References mActorExecuteInfo.
Referenced by alActorSystemFunction::addToExecutorMovement.
ActorActionKeeper * al::LiveActor::getActorActionKeeper() const
References mActorActionKeeper.
Referenced by al::startNerveAction.
Collider * al::LiveActor::getCollider() const
References mCollider.
Referenced by al::isCollidedGround, al::onCollide.
ModelKeeper * al::LiveActor::getModelKeeper() const
References mModelKeeper.
Referenced by al::calcJointPos, al::hideModel, al::tryStartMclAnimIfExist.
HitSensorKeeper * al::LiveActor::getHitSensorKeeper() const
References mHitSensorKeeper.
Referenced by al::getHitSensor, al::onDrawClipping, alSensorFunction::updateHitSensorsAll.
RailKeeper * al::LiveActor::getRailKeeper() const
References mRailKeeper.
Referenced by al::getRailDir, al::isExistRail, al::isLoopRail, al::isRailReachedGoal, al::setSyncRailToStart.
ShadowKeeper * al::LiveActor::getShadowKeeper() const
References mShadowKeeper.
Referenced by al::hideModel.
LiveActorFlag & al::LiveActor::getLiveActorFlag()
References mLiveActorFlag.
Referenced by al::hideModel, al::isAlive, al::isClipped, al::isDead, al::isInvalidClipping, al::offCollide, al::onCollide, al::onDrawClipping.
const LiveActorFlag & al::LiveActor::getLiveActorFlag() const
References mLiveActorFlag.
NerveKeeper * al::LiveActor::getNerveKeeper() const
References mNerveKeeper.
Referenced by al::initNerveAction.
void al::LiveActor::initPoseKeeper(ActorPoseKeeperBase *pPoseKeeper)
References mActorPoseKeeper.
Referenced by al::initActorPoseTFGSV, al::initActorPoseTFSV, al::initActorPoseTQSV, al::initActorPoseTRSV.
void al::LiveActor::initCollider(float radius, float yOffset, u32)
void al::LiveActor::initNerveKeeper(NerveKeeper *nk)
References mNerveKeeper.
Referenced by al::initNerve, al::initNerveAction.
void al::LiveActor::initRailKeeper(const ActorInitInfo &info)
References al::getPlacementInfo, mRailKeeper, al::tryCreateRailKeeper.
void al::LiveActor::init(const ActorInitInfo &info)
Referenced by al::initCreateActorNoPlacementInfo, al::initCreateActorWithPlacementInfo.
void al::LiveActor::initAfterPlacement()
void al::LiveActor::appear()
References makeActorAppeared.
virtual void al::LiveActor::makeActorAppeared()
Referenced by appear, al::BreakModel::appear, al::Sky::init, al::EffectObj::makeActorAppeared, alSubActorFunction::trySyncAlive.
void al::LiveActor::kill()
References makeActorDead.
Referenced by al::BreakModel::exeBreak, al::EffectObj::kill.
virtual void al::LiveActor::makeActorDead()
Referenced by al::BreakModel::init, kill, alSubActorFunction::trySyncDead.
virtual void al::LiveActor::movement()
void al::LiveActor::calcAnim()
References alLiveActorFunction::calcAnimDirect, getAudioKeeper, al::LiveActorFlag::isClipped, al::LiveActorFlag::isDead, al::LiveActorFlag::isDrawClipping, mActorPoseKeeper, mLiveActorFlag.
Referenced by al::Sky::calcAnim, alSubActorFunction::tryCalcAnim.
void al::LiveActor::draw()
virtual void al::LiveActor::startClipped()
Referenced by alSubActorFunction::trySyncClippingStart.
virtual void al::LiveActor::endClipped()
Referenced by al::invalidateClipping, alSubActorFunction::trySyncClippingEnd.
void al::LiveActor::attackSensor(HitSensor *me, HitSensor *other)
bool al::LiveActor::receiveMsg(u32 msg, HitSensor *other, HitSensor *me)
virtual const sead::Matrix34f * al::LiveActor::getBaseMtx() const
EffectKeeper * al::LiveActor::getEffectKeeper() const
References mEffectKeeper.
Referenced by alLiveActorFunction::calcAnimDirect.
AudioKeeper * al::LiveActor::getAudioKeeper() const
References mAudioKeeper.
Referenced by calcAnim.
StageSwitchKeeper * al::LiveActor::getStageSwitchKeeper() const
References mStageSwitchKeeper.
void al::LiveActor::initStageSwitchKeeper()
References mStageSwitchKeeper.
void al::LiveActor::control()
virtual void al::LiveActor::calcAndSetBaseMtx()
virtual void al::LiveActor::updateCollider()
virtual void al::LiveActor::v22()
virtual void al::LiveActor::v23()
al::LiveActor::LiveActor(const char *name)
References al::LiveActorKit::getAllActors, al::getLiveActorKit, al::LiveActorGroup::registerActor.