al::NerveStateCtrl
int al::NerveStateCtrl::mCapacity
Referenced by NerveStateCtrl.
int al::NerveStateCtrl::mStateCount
Referenced by findStateInfo.
State* al::NerveStateCtrl::mStates
Referenced by findStateInfo, NerveStateCtrl.
State* al::NerveStateCtrl::mCurrentState
Referenced by getCurrentState, isCurrentStateEnd, startState, tryEndCurrentState, updateCurrentState.
NerveStateCtrl::State * al::NerveStateCtrl::findStateInfo(const Nerve *nerve)
References mStateCount, mStates.
Referenced by startState.
const State * al::NerveStateCtrl::getCurrentState() const
References mCurrentState.
void al::NerveStateCtrl::startState(const Nerve *nerve)
References al::NerveStateBase::appear, findStateInfo, mCurrentState, al::NerveStateCtrl::State::mState.
Referenced by al::NerveKeeper::tryChangeNerve.
void al::NerveStateCtrl::tryEndCurrentState()
References isCurrentStateEnd, al::NerveStateBase::kill, mCurrentState, al::NerveStateCtrl::State::mState.
Referenced by al::NerveKeeper::tryChangeNerve.
bool al::NerveStateCtrl::updateCurrentState()
References mCurrentState, al::NerveStateCtrl::State::mState, al::NerveStateBase::update.
bool al::NerveStateCtrl::isCurrentStateEnd() const
References al::NerveStateBase::isDead, mCurrentState, al::NerveStateCtrl::State::mState.
Referenced by tryEndCurrentState.
al::NerveStateCtrl::NerveStateCtrl(int capacity)
References mCapacity, mStates.