al::NerveKeeper
IUseNerve* al::NerveKeeper::mHost
Referenced by getHost, NerveKeeper.
const Nerve* al::NerveKeeper::mEndNerve
Referenced by getCurrentNerve, setNerve, tryChangeNerve.
const Nerve* al::NerveKeeper::mNerve
Referenced by getCurrentNerve, NerveKeeper, setNerve, tryChangeNerve, update.
int al::NerveKeeper::mStep
Referenced by getStep, setNerve, tryChangeNerve, update.
NerveStateCtrl* al::NerveKeeper::mStateCtrl
Referenced by getStateCtrl, NerveKeeper, tryChangeNerve.
NerveActionCtrl* al::NerveKeeper::mActionCtrl
Referenced by getActionCtrl, initNerveAction.
const Nerve * al::NerveKeeper::getCurrentNerve() const
References mEndNerve, mNerve.
void al::NerveKeeper::initNerveAction(NerveActionCtrl *p)
References mActionCtrl.
void al::NerveKeeper::update()
References mNerve, mStep, tryChangeNerve.
Referenced by al::NerveExecutor::updateNerve.
void al::NerveKeeper::tryChangeNerve()
References mEndNerve, mNerve, mStateCtrl, mStep, al::NerveStateCtrl::startState, al::NerveStateCtrl::tryEndCurrentState.
Referenced by update.
void al::NerveKeeper::setNerve(const Nerve *nerve)
References mEndNerve, mNerve, mStep.
Referenced by alNerveFunction::setNerveAction.
IUseNerve * al::NerveKeeper::getHost()
References mHost.
int al::NerveKeeper::getStep()
References mStep.
NerveStateCtrl * al::NerveKeeper::getStateCtrl()
References mStateCtrl.
NerveActionCtrl * al::NerveKeeper::getActionCtrl()
References mActionCtrl.
Referenced by alNerveFunction::setNerveAction.
al::NerveKeeper::NerveKeeper(IUseNerve *host, const Nerve *nrv, int maxNerveStates=0)
References mHost, mNerve, mStateCtrl.