al::NerveStateBase
bool al::NerveStateBase::mIsDead
Referenced by appear, isDead, kill, update.
bool al::NerveStateBase::isDead() const
References mIsDead.
Referenced by al::NerveStateCtrl::isCurrentStateEnd.
void al::NerveStateBase::init()
void al::NerveStateBase::appear()
References mIsDead.
Referenced by al::NerveStateCtrl::startState.
void al::NerveStateBase::kill()
References mIsDead.
Referenced by al::NerveStateCtrl::tryEndCurrentState.
bool al::NerveStateBase::update()
References control, mIsDead, al::NerveExecutor::updateNerve.
Referenced by al::NerveStateCtrl::updateCurrentState.
void al::NerveStateBase::control()
Referenced by update.
al::NerveStateBase::NerveStateBase(const char *name)