al
SensorType
SensorMsg
StageSwitchType
ByamlDataType
typedef CreateFuncPtr<LiveActor>::Type al::CreateActorFuncPtr
typedef NameToCreator<CreateActorFuncPtr> al::NameToActorCreator
typedef CreateFuncPtr<AreaObj>::Type al::CreateAreaObjFuncPtr
typedef NameToCreator<CreateAreaObjFuncPtr> al::NameToAreaObjCreator
typedef CreateFuncPtr<Camera>::Type al::CreateCameraFuncPtr
typedef NameToCreator<CreateCameraFuncPtr> al::NameToCameraCreator
typedef ByamlIter al::PlacementInfo
const NameToAreaObjCreator al::staticd(sAreaObjFactoryEntries)[](sUpdateExecuteOrder)
const sead::Vector3f * al::getCameraPos()
Referenced by al::Sky::init.
void al::syncCollisionMtx(LiveActor *actor, const sead::Matrix34f *)
Referenced by alLiveActorFunction::calcAnimDirect.
bool al::isCollided(const LiveActor *actor)
bool al::isCollidedGround(const LiveActor *actor)
References al::LiveActor::getCollider, al::Collider::getGroundDistance.
bool al::isCollidedWall(const LiveActor *actor)
bool al::isOnGround(const LiveActor *actor, u32)
bool al::isPadTrigger(int port, int mask)
References fn_0024edd8.
bool al::isPadHold(int port, int mask)
bool al::isPadRelease(int port, int mask)
al::_T_BUTTON(A)
al::_T_BUTTON(B)
al::_T_BUTTON(X)
al::_T_BUTTON(Y)
al::_T_BUTTON(Home)
al::_T_BUTTON(Minus)
al::_T_BUTTON(Start)
al::_T_BUTTON(Select)
al::_T_BUTTON(L)
al::_T_BUTTON(R)
al::_T_BUTTON(Touch)
al::_T_BUTTON(Up)
al::_T_BUTTON(Down)
al::_T_BUTTON(Left)
al::_T_BUTTON(Right)
const sead::Vector2f & al::getLeftStick(int port=0)
void al::emitEffect(IUseEffectKeeper *p, const char *name, const sead::Vector3f *at=nullptr)
Referenced by al::EffectObj::makeActorAppeared.
bool al::tryEmitEffect(IUseEffectKeeper *p, const char *name)
Referenced by al::EffectObj::kill.
void al::registerExecutorUser(IUseExecutor *p, const char *name)
References al::LiveActorKit::getExecuteDirector, getLiveActorKit, al::ExecuteDirector::registerUser.
Referenced by al::HitSensorDirector::HitSensorDirector.
void al::registerExecutorFunctor(const FunctorBase &base, const char *name)
References al::LiveActorKit::getExecuteDirector, getLiveActorKit, al::ExecuteDirector::registerFunctor.
void al::registerExecutorFunctorDraw(const FunctorBase &base, const char *name)
References al::LiveActorKit::getExecuteDirector, getLiveActorKit, al::ExecuteDirector::registerFunctorDraw.
bool al::isExistArchive(const sead::SafeString &archive)
Referenced by al::EffectObjFunction::initActorEffectObj.
void al::loadArchive(const sead::SafeString &archive)
References al::SystemKit::getFileLoader, alProjectInterface::getSystemKit, al::FileLoader::loadArchive.
void al::makeLocalizedArchivePath(sead::BufferedSafeString *out, const sead::SafeString &archive)
References getLanguage.
void al::makeStageDataArchivePath(sead::BufferedSafeString *out, const char *stageName, int scenario, const char *type)
bool al::isHitCylinderSensor(HitSensor *, HitSensor *, const sead::Vector3f &, float)
const sead::Vector3f & al::getCurrentKeyTrans(const KeyPoseKeeper *p)
const sead::Vector3f & al::getNextKeyTrans(const KeyPoseKeeper *p)
const PlacementInfo * al::getNextKeyPlacementInfo(const KeyPoseKeeper *p)
void al::initLayoutActor(LayoutActor *layoutActor, const LayoutInitInfo &info, const char *archiveName, const char *=nullptr)
Referenced by al::WipeSimple::WipeSimple.
void al::startAction(LayoutActor *actor, const sead::SafeString &actionName)
Referenced by al::BreakModel::appear, al::WipeSimple::exeWait.
bool al::isActionEnd(const LayoutActor *actor)
Referenced by al::FallMapParts::exeAppear, al::BreakModel::exeBreak, al::WipeSimple::exeClose, al::WipeSimple::exeOpen.
void al::setActionFrameRate(LayoutActor *actor, float rate)
Referenced by al::WipeSimple::exeOpen.
float al::getActionFrameMax(const LayoutActor *actor)
Referenced by al::WipeSimple::exeOpen.
void al::setPaneString(LayoutActor *actor, const char *paneName, const wchar_t *text)
void al::hidePane(LayoutActor *actor, const char *paneName)
void al::initLayoutInitInfo(LayoutInitInfo *info, LiveActorKit *)
void al::startHitReaction(const LiveActor *actor, const char *name)
const PlacementInfo & al::getPlacementInfo(const ActorInitInfo &info)
Referenced by calcLinkChildNum, getLinksInfoByIndex, al::KeyPoseKeeper::init, al::FallMapParts::init, al::LiveActor::initRailKeeper, isExistRail, isObjectName, al::RailMoveMovement::RailMoveMovement, tryGetArg, tryGetArg, tryGetArg, tryGetObjectName, tryGetStringArg, tryGetTrans.
void al::initActorInitInfo(ActorInitInfo *info, const PlacementInfo *placement, const LayoutInitInfo &layoutInfo, LiveActorKit *)
void al::initActor(LiveActor *actor, const ActorInitInfo &info)
References initActorImpl, tryGetObjectName.
Referenced by al::Sky::init, al::EffectObjFunction::initActorEffectObj.
void al::initActorWithArchiveName(LiveActor *actor, const ActorInitInfo &info, const sead::SafeString &archiveName, const char *suffix=nullptr)
References initActorImpl.
Referenced by al::BreakModel::init, al::EffectObjFunction::initActorEffectObj.
void al::initActorWithArchiveNameNoPlacementInfo(LiveActor *actor, const ActorInitInfo &info, const sead::SafeString &archiveName, const char *suffix=nullptr)
void al::initMapPartsActor(LiveActor *actor, const ActorInitInfo &info)
Referenced by al::FallMapParts::init.
void al::initCreateActorNoPlacementInfo(LiveActor *actor, const ActorInitInfo &hostInfo)
References al::LiveActor::init.
void al::initCreateActorWithPlacementInfo(LiveActor *actor, const ActorInitInfo &hostInfo)
References al::LiveActor::init.
Referenced by initPlacementMap.
void al::initActorPoseTFSV(LiveActor *actor)
References al::LiveActor::initPoseKeeper.
void al::initActorPoseTFGSV(LiveActor *actor)
References al::LiveActor::initPoseKeeper.
void al::initActorPoseTQSV(LiveActor *actor)
References al::LiveActor::initPoseKeeper.
Referenced by al::FallMapParts::init.
void al::initActorPoseTRSV(LiveActor *actor)
References al::LiveActor::initPoseKeeper.
void al::resetPosition(LiveActor *actor)
Referenced by al::FallMapParts::exeEnd.
void al::setTrans(LiveActor *actor, const sead::Vector3f &trans)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getTransPtr.
Referenced by al::Sky::calcAnim, al::FallMapParts::exeEnd, al::FallMapParts::exeFall, setSyncRailToStart.
void al::setRotate(LiveActor *actor, const sead::Vector3f &rotate)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getRotatePtr.
void al::setScale(LiveActor *actor, const sead::Vector3f &scale)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getScalePtr.
void al::setVelocity(LiveActor *actor, const sead::Vector3f &velocity)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getVelocityPtr.
void al::addVelocityToGravity(LiveActor *actor, float amount)
Referenced by al::FallMapParts::exeFall.
void al::scaleVelocity(LiveActor *actor, float amount)
Referenced by al::FallMapParts::exeFall.
void al::setVelocityZero(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getVelocityPtr.
Referenced by al::FallMapParts::exeEnd.
void al::setFront(LiveActor *actor, const sead::Vector3f &front)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getFrontPtr.
void al::setQuat(LiveActor *actor, const sead::Quatf &quat)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getQuatPtr.
void al::setGravity(LiveActor *actor, const sead::Vector3f &gravity)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getGravityPtr.
const sead::Vector3f & al::getTrans(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getTrans.
Referenced by al::FallMapParts::init.
const sead::Vector3f & al::getRotate(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getRotate.
const sead::Vector3f & al::getScale(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getScale.
const sead::Vector3f & al::getVelocity(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getVelocity.
const sead::Vector3f & al::getFront(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getFront.
const sead::Quatf & al::getQuat(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getQuat.
const sead::Vector3f & al::getGravity(const LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getGravity.
sead::Vector3f * al::getTransPtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getTransPtr.
sead::Vector3f * al::getRotatePtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getRotatePtr.
sead::Vector3f * al::getScalePtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getScalePtr.
sead::Vector3f * al::getVelocityPtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getVelocityPtr.
sead::Vector3f * al::getFrontPtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getFrontPtr.
sead::Quatf * al::getQuatPtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getQuatPtr.
sead::Vector3f * al::getGravityPtr(LiveActor *actor)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::getGravityPtr.
void al::makeMtxSRT(sead::Matrix34f *out, const LiveActor *actor)
Referenced by al::EffectObj::control, al::EffectObjFunction::initActorEffectObj, al::EffectObj::makeActorAppeared.
void al::updatePoseRotate(LiveActor *actor, const sead::Vector3f &rotate)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::updatePoseRotate.
void al::updatePoseQuat(LiveActor *actor, const sead::Quatf &quat)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::updatePoseQuat.
void al::updatePoseMtx(LiveActor *actor, const sead::Matrix34f *mtx)
References al::LiveActor::getActorPoseKeeper, al::ActorPoseKeeperBase::updatePoseMtx.
Referenced by al::BreakModel::appear.
void al::copyPose(LiveActor *to, const LiveActor *from)
Referenced by al::BreakModel::appear.
void al::calcSideDir(sead::Vector3f *out, const LiveActor *actor)
References al::ActorPoseKeeperBase::calcBaseMtx, al::LiveActor::getActorPoseKeeper.
void al::calcUpDir(sead::Vector3f *out, const LiveActor *actor)
References al::ActorPoseKeeperBase::calcBaseMtx, al::LiveActor::getActorPoseKeeper.
void al::calcFrontDir(sead::Vector3f *out, const LiveActor *actor)
References al::ActorPoseKeeperBase::calcBaseMtx, al::LiveActor::getActorPoseKeeper.
bool al::isSensorName(HitSensor *sensor, const char *name)
References isEqualString.
bool al::isSensorPlayer(const HitSensor *sensor)
References SensorType_Player, SensorType_PlayerFireBall.
bool al::isSensorRide(const HitSensor *sensor)
References SensorType_Ride.
bool al::isSensorEnemy(const HitSensor *sensor)
References SensorType_Dossun, SensorType_Enemy, SensorType_EnemyAttack, SensorType_EnemyBody, SensorType_KillerMagnum.
bool al::isSensorEnemyBody(const HitSensor *sensor)
References SensorType_EnemyBody.
bool al::isSensorEnemyAttack(const HitSensor *sensor)
References SensorType_EnemyAttack.
bool al::isSensorSimple(const HitSensor *sensor)
References SensorType_Bindable, SensorType_EnemySimple, SensorType_MapObjSimple.
bool al::isSensorMapObj(const HitSensor *sensor)
References SensorType_MapObj.
void al::initActorSRTAndPoseTRSV(LiveActor *actor, const ActorInitInfo &info)
void al::startAction(LiveActor *actor, const char *actionName)
bool al::tryStartAction(LiveActor *actor, const char *actionName)
Referenced by al::FallMapParts::exeAppear, al::FallMapParts::exeEnd, al::FallMapParts::exeFall, al::FallMapParts::exeWait.
bool al::isActionEnd(const LiveActor *actor)
void al::startNerveAction(LiveActor *actor, const char *actionName)
References al::LiveActor::getActorActionKeeper, alNerveFunction::setNerveAction, al::ActorActionKeeper::tryStartActionNoAnim.
Referenced by initNerveAction.
bool al::tryStartSklAnimIfExist(LiveActor *actor, const char *animName)
bool al::tryStartMtsAnimIfExist(LiveActor *actor, const char *animName)
bool al::tryStartMtpAnimIfExist(LiveActor *actor, const char *animName)
bool al::tryStartMclAnimIfExist(LiveActor *actor, const char *animName)
References alModelCtr::getMclAnimPlayer, al::ModelKeeper::getModel, al::LiveActor::getModelKeeper, al::AnimPlayerSimple::startAnim.
bool al::tryStartVisAnimIfExist(LiveActor *actor, const char *animName)
void al::setBaseMtxAndCalcAnim(LiveActor *actor, const sead::Matrix34f &, const sead::Vector3f &)
Referenced by alLiveActorFunction::calcAnimDirect.
bool al::isClipped(const LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isClipped.
Referenced by hideModel, invalidateClipping, onDrawClipping, alSubActorFunction::trySyncClippingEnd, alSubActorFunction::trySyncClippingStart.
bool al::isInvalidClipping(const LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isInvalidClipping.
Referenced by invalidateClipping, validateClipping.
bool al::isDead(const LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isDead.
Referenced by al::HitSensorKeeper::attackSensor.
bool al::isAlive(const LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isDead.
Referenced by hideModel, alSubActorFunction::tryCalcAnim, alSubActorFunction::trySyncClippingEnd, alSubActorFunction::trySyncClippingStart.
void al::onCollide(LiveActor *actor)
References al::LiveActor::getCollider, al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isOffCollide.
void al::offCollide(LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActorFlag::isOffCollide.
void al::onDrawClipping(LiveActor *actor)
References alActorSystemFunction::addToExecutorMovement, al::LiveActor::getHitSensorKeeper, al::LiveActor::getLiveActorFlag, isClipped, al::LiveActorFlag::isDrawClipping, alSensorFunction::updateHitSensorsAll, al::HitSensorKeeper::validateBySystem.
void al::invalidateClipping(LiveActor *actor)
References al::LiveActor::endClipped, al::ClippingDirector::getClippingActorHolder, al::LiveActorKit::getClippingDirector, getLiveActorKit, al::ClippingActorHolder::invalidateClipping, isClipped, isInvalidClipping.
Referenced by al::BreakModel::init, al::Sky::init, al::FallMapParts::receiveMsg.
void al::validateClipping(LiveActor *actor)
References al::ClippingDirector::getClippingActorHolder, al::LiveActorKit::getClippingDirector, getLiveActorKit, isInvalidClipping, al::ClippingActorHolder::validateClipping.
Referenced by al::FallMapParts::exeWait.
void al::invalidateCollisionPartsBySystem(LiveActor *actor)
Referenced by al::FallMapParts::exeEnd.
void al::validateCollisionPartsBySystem(LiveActor *actor)
Referenced by al::FallMapParts::exeAppear.
void al::showModel(LiveActor *actor)
Referenced by al::FallMapParts::exeEnd.
void al::hideModel(LiveActor *actor)
References al::LiveActor::getLiveActorFlag, al::LiveActor::getModelKeeper, al::LiveActor::getShadowKeeper, al::ModelKeeper::hide, hideShadow, isAlive, isClipped, al::LiveActorFlag::isHideModel, alActorSystemFunction::removeFromExecutorDraw.
Referenced by al::FallMapParts::exeEnd.
void al::showShadow(LiveActor *actor)
void al::hideShadow(LiveActor *actor)
Referenced by hideModel.
const sead::Matrix34f * al::getJointMtxPtr(const LiveActor *actor, const char *jointName)
Referenced by calcJointPos.
void al::calcJointPos(sead::Vector3f *out, const LiveActor *actor, const char *jointName)
References getJointMtxPtr, al::LiveActor::getModelKeeper.
void al::initNerve(LiveActor *actor, const Nerve *nerve, int maxNerveStates=0)
References al::LiveActor::initNerveKeeper.
Referenced by al::FallMapParts::init, al::BreakModel::init, al::RailMoveMovement::RailMoveMovement.
void al::initNerveAction(LiveActor *actor, const char *name, alNerveFunction::NerveActionCollector *collector, int maxNerveStates=0)
References al::LiveActor::getNerveKeeper, al::LiveActor::initNerveKeeper, startNerveAction.
HitSensor * al::getHitSensor(const LiveActor *actor, const char *name)
References al::LiveActor::getHitSensorKeeper, al::HitSensorKeeper::getSensor.
Referenced by getSensorRadius.
float al::getSensorRadius(const LiveActor *actor, const char *sensorName)
References getHitSensor, al::HitSensor::getRadius.
void al::initActorEffectKeeper(LiveActor *actor, const ActorInitInfo &info, const char *)
Referenced by al::EffectObjFunction::initActorEffectObj.
void al::trySyncStageSwitchAppear(LiveActor *actor)
Referenced by al::FallMapParts::init, al::Sky::init, al::EffectObjFunction::initActorEffectObj.
void al::trySyncStageSwitchKill(LiveActor *actor)
void al::rotateQuatXDirDegree(LiveActor *actor, const sead::Quatf &from, float degrees)
void al::rotateQuatYDirDegree(LiveActor *actor, const sead::Quatf &from, float degrees)
void al::rotateQuatZDirDegree(LiveActor *actor, const sead::Quatf &from, float degrees)
void al::calcQuatSide(sead::Vector3f *out, const LiveActor *from)
void al::initLiveActorKit(LiveActorKit *kit)
References getApplication, Application::setLiveActorKit.
LiveActorKit * al::getLiveActorKit()
References getApplication, Application::getLiveActorKit.
Referenced by invalidateClipping, al::LiveActor::LiveActor, registerExecutorFunctor, registerExecutorFunctorDraw, registerExecutorUser, validateClipping.
void al::executeDraw(const LiveActorKit *kit, const char *)
void al::executeDrawList(const LiveActorKit *kit, const char *, const char *)
u32 al::calcHashCode(const char *str)
bool al::isNearZero(float value, float range=.001)
Referenced by al::RailRider::isReachedGoal.
void al::preScaleMtx(sead::Matrix34f *out, const sead::Vector3f &)
Referenced by alLiveActorFunction::calcAnimDirect.
void al::calcMtxLocalTrans(sead::Vector3f *out, const sead::Matrix34f &mtx, const sead::Vector3f &trans)
void al::rotateQuatXDirDegree(sead::Quatf *out, const sead::Quatf &from, float degrees)
void al::rotateQuatYDirDegree(sead::Quatf *out, const sead::Quatf &from, float degrees)
void al::rotateQuatZDirDegree(sead::Quatf *out, const sead::Quatf &from, float degrees)
void al::calcQuatSide(sead::Vector3f *out, const sead::Quatf &from)
void al::initRandomSeed(u32 seed)
void al::lerpVec(sead::Vector3f *out, const sead::Vector3f &from, const sead::Vector3f &to, float amount)
void al::createSequenceHeap()
void al::createSceneResourceHeap(const char *stageName)
void al::createSceneHeap(const char *stageName)
void al::createCourseSelectHeap()
sead::ExpHeap * al::getStationedHeap()
References al::SystemKit::getMemorySystem, al::MemorySystem::getStationedHeap, alProjectInterface::getSystemKit.
sead::ExpHeap * al::getSequenceHeap()
References al::SystemKit::getMemorySystem, al::MemorySystem::getSequenceHeap, alProjectInterface::getSystemKit.
sead::FrameHeap * al::getSceneResourceHeap()
References al::SystemKit::getMemorySystem, al::MemorySystem::getSceneResourceHeap, alProjectInterface::getSystemKit.
Referenced by isCreatedSceneResourceHeap.
sead::FrameHeap * al::getSceneHeap()
sead::FrameHeap * al::getCourseSelectHeap()
References al::MemorySystem::getCourseSelectHeap, al::SystemKit::getMemorySystem, alProjectInterface::getSystemKit.
sead::FrameHeap * al::getCourseSelectResourceHeap()
void al::destroySceneHeap()
bool al::isCreatedSceneResourceHeap()
References getSceneResourceHeap.
const char * al::getLanguage()
Referenced by makeLocalizedArchivePath.
const sead::Matrix34f * al::getJointMtxPtr(ModelKeeper *keeper, const char *jointName)
void al::setNerve(IUseNerve *p, const Nerve *nerve)
Referenced by al::BreakModel::appear, al::FallMapParts::exeAppear, al::WipeSimple::exeClose, al::FallMapParts::exeEnd, al::FallMapParts::exeFall, al::FallMapParts::receiveMsg, updateNerveStateAndNextNerve.
bool al::isStep(IUseNerve *p, int step)
bool al::isNerve(const IUseNerve *p, const Nerve *nerve)
Referenced by al::FallMapParts::receiveMsg.
bool al::isFirstStep(const IUseNerve *p)
Referenced by al::FallMapParts::exeAppear, al::WipeSimple::exeClose, al::FallMapParts::exeEnd, al::FallMapParts::exeFall, al::WipeSimple::exeOpen, al::WipeSimple::exeWait, al::FallMapParts::exeWait.
bool al::isLessStep(const IUseNerve *p, int step)
int al::getNerveStep(const IUseNerve *p)
bool al::isGreaterStep(const IUseNerve *p, int step)
Referenced by al::FallMapParts::exeEnd, al::FallMapParts::exeFall.
bool al::isGreaterEqualStep(const IUseNerve *p, int step)
void al::initNerveState(IUseNerve *p, NerveStateBase *state, const Nerve *stateNrv, const char *name)
bool al::updateNerveState(IUseNerve *p)
bool al::updateNerveStateAndNextNerve(IUseNerve *p, const Nerve *nerve)
References setNerve.
bool al::isPlaced(const ActorInitInfo &info)
bool al::tryGetArg(bool *out, const PlacementInfo &info, const char *argName)
Referenced by al::RailMoveMovement::RailMoveMovement, tryGetArg, tryGetArg, tryGetArg.
bool al::tryGetArg(float *out, const PlacementInfo &info, const char *argName)
bool al::tryGetArg(int *out, const PlacementInfo &info, const char *argName)
bool al::tryGetArg(bool *out, const ActorInitInfo &info, const char *argName)
References getPlacementInfo, tryGetArg.
bool al::tryGetArg(float *out, const ActorInitInfo &info, const char *argName)
References getPlacementInfo, tryGetArg.
bool al::tryGetArg(int *out, const ActorInitInfo &info, const char *argName)
References getPlacementInfo, tryGetArg.
bool al::tryGetArg0(int *out, const PlacementInfo &info)
Referenced by al::FallMapParts::init.
bool al::tryGetArg0(float *out, const ActorInitInfo &info)
bool al::tryGetArg1(float *out, const ActorInitInfo &info)
bool al::tryGetArg3(int *out, const ActorInitInfo &info)
Referenced by al::KeyPoseKeeper::init.
bool al::tryGetStringArg(const char **out, const ActorInitInfo &info, const char *argName)
References getPlacementInfo, tryGetStringArg.
Referenced by tryGetStringArg.
bool al::tryGetStringArg(const char **out, const PlacementInfo &info, const char *argName)
References isEqualString.
bool al::tryGetObjectName(const char **out, const ActorInitInfo &info)
References getPlacementInfo, tryGetObjectName.
Referenced by getLinksActorObjectName, al::EffectObj::init, initActor, initPlacementMap, isObjectName, tryGetObjectName.
bool al::tryGetObjectName(const char **out, const PlacementInfo &info)
bool al::isObjectName(const ActorInitInfo &info, const char *objectName)
References getPlacementInfo, isObjectName.
Referenced by isObjectName.
bool al::isObjectName(const PlacementInfo &info, const char *objectName)
References isEqualString, tryGetObjectName.
int al::calcLinkChildNum(const ActorInitInfo &info)
References getPlacementInfo.
Referenced by al::KeyPoseKeeper::init.
bool al::tryGetTrans(sead::Vector3f *out, const ActorInitInfo &info)
References getPlacementInfo, tryGetTrans.
Referenced by al::KeyPose::init, tryGetTrans.
bool al::tryGetTrans(sead::Vector3f *out, const PlacementInfo &info)
bool al::tryGetQuat(sead::Quatf *out, const PlacementInfo &info)
Referenced by al::KeyPose::init.
bool al::isExistRail(const ActorInitInfo &info)
References getPlacementInfo, tryGetRailIter.
Referenced by al::RailMoveMovement::exeMove.
bool al::tryGetRailIter(PlacementInfo *out, const PlacementInfo &info)
Referenced by isExistRail.
bool al::getLinksInfoByIndex(PlacementInfo *out, const ActorInitInfo &info, int index)
References getPlacementInfo.
Referenced by getLinksActorObjectName, al::KeyPoseKeeper::init.
const char * al::getLinksActorObjectName(const ActorInitInfo &info, int index)
References getLinksInfoByIndex, tryGetObjectName.
void al::setSyncRailToStart(LiveActor *actor)
References al::RailRider::getCurrentPos, al::LiveActor::getRailKeeper, al::RailKeeper::getRailRider, al::RailRider::moveToRailStart, setTrans.
const sead::Vector3f & al::getRailDir(const LiveActor *actor)
References al::RailRider::getCurrentDir, al::LiveActor::getRailKeeper, al::RailKeeper::getRailRider.
bool al::isRailReachedGoal(const LiveActor *actor)
References al::LiveActor::getRailKeeper, al::RailKeeper::getRailRider, al::RailRider::isReachedGoal.
void al::moveSyncRail(LiveActor *actor, float speed)
Referenced by al::RailMoveMovement::exeMove.
void al::moveSyncRailTurn(LiveActor *actor, float speed)
Referenced by al::RailMoveMovement::exeMove.
void al::moveSyncRailLoop(LiveActor *actor, float speed)
Referenced by al::RailMoveMovement::exeMove.
bool al::isLoopRail(const LiveActor *actor)
References al::LiveActor::getRailKeeper, al::RailKeeper::getRailRider, al::RailRider::isLoop.
bool al::isExistRail(const LiveActor *actor)
References al::LiveActor::getRailKeeper, al::RailKeeper::isExistRail.
RailKeeper * al::tryCreateRailKeeper(const PlacementInfo &info)
Referenced by al::LiveActor::initRailKeeper.
Resource * al::findOrCreateResource(const sead::SafeString &archive)
Referenced by al::ActorFactory::ActorFactory, al::MemorySystem::createSceneResourceHeap.
void al::initPlacementMap(Scene *scene, const Resource *stageArchive, const ActorInitInfo &infoTemplate, const char *infoIterName)
References initCreateActorWithPlacementInfo, tryGetObjectName, tryGetPlacementInfo.
bool al::tryGetPlacementInfo(PlacementInfo *out, const Resource *stageArchive, const char *infoIterName)
Referenced by initPlacementMap.
SceneObjHolder * al::getSceneObjHolder()
References getApplication, Application::getSceneObjHolder.
Referenced by createSceneObj, getSceneObj, isExistSceneObj, setSceneObj.
ISceneObj * al::createSceneObj(int id)
References al::SceneObjHolder::create, getSceneObjHolder.
ISceneObj * al::getSceneObj(int id)
References al::SceneObjHolder::getObj, getSceneObjHolder.
bool al::isExistSceneObj(int id)
References getSceneObjHolder, al::SceneObjHolder::isExist.
void al::setSceneObj(ISceneObj *obj, int id)
References getSceneObjHolder, al::SceneObjHolder::setObj.
void al::stopScene(int frames)
void al::startSe(IUseAudioKeeper *p, const sead::SafeString &name)
bool al::tryStartSe(IUseAudioKeeper *p, const sead::SafeString &name, int)
Referenced by al::EffectObj::control.
void al::initStageSwitchAppear(IUseStageSwitch *p, const ActorInitInfo &info)
Referenced by al::FallMapParts::init, al::Sky::init.
void al::initStageSwitchKill(IUseStageSwitch *p, const ActorInitInfo &info)
void al::initStageSwitchA(IUseStageSwitch *p, const ActorInitInfo &info)
void al::initStageSwitchB(IUseStageSwitch *p, const ActorInitInfo &info)
bool al::isOnSwitchA(IUseStageSwitch *p)
bool al::listenStageSwitchOnAppear(IUseStageSwitch *p, const FunctorBase &onFunctor, const FunctorBase &offFunctor)
const char * al::getStageSwitchName(StageSwitchType type)
References StageSwitchType_A, StageSwitchType_Appear, StageSwitchType_B, StageSwitchType_DeadOn, StageSwitchType_Kill.
Referenced by al::StageSwitchAccesser::initWithPlacementInfo.
void al::createAndStartInitializeThread(sead::Heap *heap, int stackSize, const FunctorBase &func)
Application * al::getApplication()
Referenced by getLiveActorKit, getSceneObjHolder, alProjectInterface::getSystemKit, initLiveActorKit.
const char * al::getBaseName(const char *name)
const char * al::createStringIfInStack(const char *str)
References isInStack.
bool al::isEqualString(const char *s1, const char *s2)
Referenced by al::MemorySystem::createSceneResourceHeap, al::NerveActionCtrl::findNerve, alSensorFunction::findSensorTypeByName, al::HitSensorKeeper::getSensor, isEqualString, isObjectName, isSensorName, tryGetStringArg.
bool al::isEqualString(const sead::SafeString &s1, const sead::SafeString &s2)
References isEqualString.
bool al::isEqualSubString(const char *str, const char *substr)
bool al::isInStack(const void *ptr)
Referenced by createStringIfInStack.
const u32 * al::fn_0024edd8()
Referenced by isPadTrigger.
al::_T_BUTTON(LeftStickUp)
al::_T_BUTTON(LeftStickDown)
al::_T_BUTTON(LeftStickLeft)
al::_T_BUTTON(LeftStickRight)
static const ExecuteOrder al::staticd(sDraw0ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw1ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw2ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw3ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw4ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw5ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw6ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw7ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw8ExecuteOrder)
static const ExecuteOrder al::staticd(sDraw9ExecuteOrder)
LiveActor * al::createActorFunction(const char *name)
const NameToActorCreator al::staticd(sActorFactoryEntries)[]
AreaObj * al::createAreaObjFunction(const char *name)
const NameToAreaObjCreator al::staticd(sAreaObjFactoryEntries)[]
void al::initActorInitInfo(ActorInitInfo *info, const PlacementInfo *placement, const ActorInitInfo &baseInfo)
static void al::initActorImpl(LiveActor *actor, const ActorInitInfo &info, const sead::SafeString &objectName, const sead::SafeString &archivePath, const char *suffix=nullptr)
Referenced by initActor, initActorWithArchiveName.
void al::fn_00240350()
Referenced by al::LiveActorKit::endInit.
void al::fn_001e8a64()
Referenced by al::LiveActorKit::endInit.
void al::fn_001cc9b0(const char *, const FunctorV0F &)
Referenced by al::LiveActorKit::endInit.
bool al::fn_00268df8(IUseAudioKeeper *, const sead::SafeString &name)
Referenced by al::FallMapParts::exeFall.
void al::fn_002911e8(sead::FrameHeap **out, u32 heapSize, const char *name, u8, int)
Referenced by al::MemorySystem::createSceneResourceHeap.
char * al::removeExtensionString(char *res, size_t size, const char *str)