alProjectInterface
al::SystemKit * alProjectInterface::getSystemKit()
References al::getApplication, Application::getSystemKit.
Referenced by al::getCourseSelectHeap, al::getSceneResourceHeap, al::getSequenceHeap, al::getStationedHeap, al::loadArchive.