Fugumannen.cpp
void fn_0027b51c(al::LiveActor *, const al::ActorInitInfo &info, int)
Referenced by Fugumannen::init.
void fn_0027ee34(al::LiveActor *, const al::ActorInitInfo &info, int)
Referenced by Fugumannen::init.
bool fn_0027b768(u32, al::HitSensor *, al::HitSensor *, al::NerveStateBase *, const al::Nerve *)
Referenced by Fugumannen::receiveMsg.
bool fn_0027b704(u32, al::HitSensor *, al::HitSensor *, al::NerveStateBase *)
Referenced by Fugumannen::receiveMsg.
void fn_00240e08(al::LiveActor *, const sead::Vector3f &, float)
Referenced by Fugumannen::exeMove, Fugumannen::exeMove2.
void fn_002cd428(al::LiveActor *, al::NerveStateBase *)
Referenced by Fugumannen::exeBlowDown.