Togezo.cpp
static WalkerStateParam split() sTogezoWalkerStateParam(4.0, 0.98, 0.85, 250.0, 700.0, 180.0, 70.0, 150.0)
Referenced by Togezo::exeAttack, Togezo::exeSearch, Togezo::exeTurn, Togezo::exeWander, Togezo::init.
static WalkerStateWanderParam split() sTogezoWalkerStateWanderParam(30, 90, 0.7, 4.0, 10.0, "Walk", "Wait")
Referenced by Togezo::init.
static WalkerStateChaseParam split() sTogezoWalkerStateChaseParam(false, true, 1.3, 30.0, 150.0, 3.0, 20.0, "Run", "Wait")
Referenced by Togezo::init.
void fn_0027a1a0(al::LiveActor *actor, const char *)
Referenced by Togezo::init.
void fn_0027cf20(al::LiveActor *actor, const al::ActorInitInfo &info, int)
Referenced by Togezo::init.
bool fn_00272a9c()
Referenced by Togezo::exeSearch, Togezo::exeTurn, Togezo::exeWander.
bool fn_00259758(al::LiveActor *, const sead::Vector3f &, const WalkerStateParam *)
Referenced by Togezo::exeWander.
bool fn_00262988(al::LiveActor *, sead::Vector3f *out, const sead::Vector3f &, float)
Referenced by Togezo::exeSearch, Togezo::exeTurn.
void fn_00258774(Togezo *, const WalkerStateParam *)
Referenced by Togezo::exeAttack, Togezo::exeSearch, Togezo::exeTurn.
bool fn_0026b6cc(WalkerStateWander *, const sead::Vector3f &trans)
Referenced by Togezo::exeChase.
void fn_00279158(Togezo *, const EnemyStateBlowDown *)
Referenced by Togezo::exeBlowDown.