TrickHintPanel.cpp
u32 fn_002278CC(al::LiveActor *actor, char *str)
Referenced by TrickHintPanel::init.
int fn_0026A9B8(u32)
Referenced by TrickHintPanel::exeOn.
int fn_0026AA60(u32)
Referenced by TrickHintPanel::exeOff.
int fn_002786F4()
Referenced by TrickHintPanel::exenrv3, TrickHintPanel::exeOff.