IUsePlayerAnimator
virtual void IUsePlayerAnimator::v_0()=0
virtual void IUsePlayerAnimator::v_4()=0
virtual void IUsePlayerAnimator::v_8()=0
virtual void IUsePlayerAnimator::v_C()=0
virtual void IUsePlayerAnimator::v_10()=0
virtual bool IUsePlayerAnimator::isAnimEnd() const =0
Referenced by PlayerActionConditionAnimEnd::check.
virtual bool IUsePlayerAnimator::isAnim(const sead::SafeString &name)=0
Referenced by PlayerActionConditionAnimEnd::check.
virtual float IUsePlayerAnimator::getAnimFrame() const =0
Referenced by PlayerActionConditionAnimEnd::check.
virtual void IUsePlayerAnimator::v_20()=0
virtual void IUsePlayerAnimator::v_24()=0
virtual void IUsePlayerAnimator::v_28()=0
virtual void IUsePlayerAnimator::v_2C()=0
virtual void IUsePlayerAnimator::v_30()=0
virtual void IUsePlayerAnimator::v_34()=0
virtual void IUsePlayerAnimator::v_38()=0
virtual void IUsePlayerAnimator::v_3C()=0
virtual void IUsePlayerAnimator::v_40()=0
virtual void IUsePlayerAnimator::v_44()=0
virtual void IUsePlayerAnimator::v_48()=0
virtual void IUsePlayerAnimator::v_4C()=0