rp
void rp::createCoinRotater()
References SceneObjType_CoinRotater.
Referenced by NoteObj::NoteObj, NoteObj::NoteObj.
float rp::getCoinRotateY()
References CoinRotater::getRotateY, SceneObjType_CoinRotater.
Referenced by NoteObj::control.
PlayerActor * rp::getPlayerActor()
Referenced by getPlayerPos.
const sead::Vector3f & rp::getPlayerPos()
References getPlayerActor.
Referenced by Togezo::exeSearch, Togezo::exeTurn.
CourseList * rp::getCourseList()
void rp::requestHitReactionToAttacker(u32 msg, const al::HitSensor *, const al::HitSensor *)
Referenced by GhostPlayer::receiveMsg.