#!/usr/bin/env python3
import os
import shutil

import tools.splector as splector
import tools.splector.split

from tools.low.glob import *
from tools.low.readSymMap import *
from tools.pypstem._utils import *
from tools.pypstem.callProcess import *
from tools.pypstem.manSetup import setup_compiler

flags_asm = default_flags_comp
flags_asm.extend(default_flags_comp_asm)
if cfg.flags_compile:
    flags_asm.extend(cfg.flags_compile)
if cfg.flags_compile_asm:
    flags_asm.extend(cfg.flags_compile_asm)

def isSymMapDiff():
    if not getMapFile().exists():
        fail ("Version not configured, cannot split.")

    ts_new = int(getMapFile().stat().st_mtime)

    def write_new():
        with open(getCfgMapFile(), "w") as f:
            f.write(f"{getVersion()} {ts_new}")

    if not getCfgMapFile().exists():
        write_new()
        return True

    ts_old = 0
    ver_old = 0
    with open(getCfgMapFile(), "r") as f:
        ver_old, ts_old = next(f).split()

    if getVersion() != ver_old:
        write_new()
        return True
    if int(ts_old) != ts_new:
        write_new()
        return True

    return False

def write_depend():
    # get all functions
    #func_list = [sym[MapFmt.Symbol] or f"fn_{sym[MapFmt.Start]:08X}" for sym in read_sym_file() if "f" in sym[MapFmt.Type]]

    # write depends.s
    in_depend = getDependFile().with_suffix(".s")
    with open(in_depend, "w") as f:
        #for func in func_list:
        #    f.write(f"    IMPORT {func}\n")
        f.write("    IMPORT __ctr_start\n")
        f.write("\n    PRESERVE8\n    END\n")

    # compile depends.o
    asm_flags = flags_asm + ["-o", str(getDependFile()), str(in_depend)]
    do_assemble(asm_flags)

def write_stubs():
    if (getBuildLibPath() / "libstubs.a").exists() and not isSymMapDiff():
        return

    # write stubs.c
    with open(getSplitPath() / "stub.c", "w") as f:
        f.write(f"/*\n\tStub file for {cfg.project_name}\n")
        f.write( "\tAutogenerated, please dont modify!\n*/\n\n")
        f.write("#define STUB(S) __weak __attribute__((section(\"i.\" #S))) void S() { __nop(); __nop(); __nop(); }\n")
        #f.write("#define STUB_G(S) void S() { __nop(); __nop(); __nop(); }\n")
        f.write( "\n")

        for sym in read_sym_file():
            if not "f" in sym[MapFmt.Type] or "g" in sym[MapFmt.Type]:
                continue

            func = sym[MapFmt.Symbol]
            if not func:
                continue

            f.write(f"STUB({func});\n")

    # add stubs module
    cfg.modules[str(getSplitPath().relative_to(getProjDir()))] = {"name": "stubs", "extensions": set(["c"]), "source_dir": ".", "flags": ["--keep"]}

def exec_split(clear=False):
    if not cfg.do_split:
        write_stubs()
        write_depend()
        return

    if not clear and getSplitLibFile().exists() and (getSplitAsmDir().exists() and cfg.keep_objects):# and not isSymMapDiff():
        echo ("Assembly up to date")
        return

    echo ("Splector11 (may take a few minutes)!")
    if not clear:
        echo (" if you need to regenerate it later, run with \'-cs\'.")

    if getSplitAsmDir().exists():
        shutil.rmtree(getSplitAsmDir(), ignore_errors=True)
    if getSplitObjDir().exists():
        shutil.rmtree(getSplitObjDir(), ignore_errors=True)
    
    splector.split.run()

    if not getSplitAsmDir().exists():
        fail ("Splits are missing.")

    echo ("Recompiling splits")

    setup_compiler(cfg.compiler)

    getSplitObjDir().mkdir(parents=True, exist_ok=True)

    for asm in getSplitAsmDir().rglob("*.s"):
        output = getSplitObjDir() / asm.with_suffix(".o").name
        echo (f"> {output.name} <", "\r")

        asm_flags = flags_asm + ["-o", str(output), str(asm)]
        do_assemble(asm_flags)

        if not asm.name.startswith("a"):
            echo (f"Unknown file in split asm: {asm} (ignored)")
            asm.replace(asm.with_suffix(p.suffix + "_b"))

    echo ("Prelinking recomp")

    # generate .via
    via_path = getSplitPath() / "splector.via"

    with open(via_path, "w") as f:
        for s in getSplitObjDir().glob("*.o"):
            f.write(str(s))
            f.write(" ")

    out_name = str(getSplitObjFile())

    # prelink all objs
    flags_link = default_flags_link + ["--partial", f"--output={out_name}", f"--via={via_path}", "--no_map", "--no_symbols", "--no_locals"]
    do_link(flags_link, True)

    if not getSplitObjFile().exists():
        fail ("Splector recompilation is missing.")

    # strip debug
    flags_strip = [out_name, "--elf", "--strip=debug,comment,notes", "--output", out_name]
    do_export(flags_strip)

    if not getSplitObjFile().exists():
        fail ("Splector recompilation went missing while stripping.")

    # generate archive
    echo ("Archiving recomp")
    ar_path = str(getSplitLibFile())

    getBuildLibPath().mkdir(parents=True, exist_ok=True)

    flags_ar = ["-rcs", ar_path, str(getSplitObjFile())]
    do_archive(flags_ar)

    # cleanup
    if not cfg.keep_objects:
        shutil.rmtree(getSplitPath(), ignore_errors=True)

