crt0.cpp
unsigned char Image$$ZI$$ZI$$Base[][]
Referenced by nninitRegion.
unsigned char Image$$ZI$$ZI$$Limit[][]
Referenced by nninitRegion.
__asm void nninitRegion()
References Image$$ZI$$ZI$$Base, Image$$ZI$$ZI$$Limit.
Referenced by __ctr_start.
void nninitLocale()
References __rt_locale.
Referenced by __ctr_start.
void nninitSystem()
Referenced by __ctr_start.
void nninitStartUp()
Referenced by __ctr_start.
__weak void __cpp_initialize_aeabi_()
Referenced by __ctr_start.
unsigned int * __rt_locale(void)
Referenced by nninitLocale.
void nninitCallStaticInitializers()
Referenced by __ctr_start.
void nninitSetup()
Referenced by __ctr_start.
void nnMain()
Referenced by __ctr_start.
__asm void __ctr_start()
References __cpp_initialize_aeabi_, nn::svc::ExitProcess, nninitCallStaticInitializers, nninitLocale, nninitRegion, nninitSetup, nninitStartUp, nninitSystem, nnMain.